version: '3'
services:
  db:
     image: mariadb
     container_name: db
     restart: always
     environment:
        - MYSQL_ROOT_PASSWORD="secret"
        - MARIADB_DATABASE=fail
        - MARIADB_USER=fail
        - MARIADB_PASSWORD=fail
     volumes:
        - ./db:/var/lib/mysql

  shell:
    image: danceos/fail-ci-build
    container_name: shell
    stdin_open: true # docker run -i
    restart: "no"
    tty: true        # docker run -t
    entrypoint: ["bash", "-c", "while :; do :; done & kill -STOP $$! && wait $$!"]
    links:
      - db
    working_dir: /home/fail/fail-targets
    volumes:
      - .:/home/fail/fail-targets
      - ./fail:/home/fail/fail


